### ISSUE TITLE
Can influxdb monitor several cadivisor at the same time

### ISSUE THREAD

**Issue by mysterytree** [Kentik/docker-monitor#1]
Thanks for your share.
How to monitoring containers in serveral vm confused me a lot recently. 
I had tried cadvisor+prometheus+promdash.
But some problems occured when useing  prom query  .
Now I want to try cadivsor + influxdb + grafana.
Could you tell me  whether influxdb and grafana monitor several cadivisor at the same time like prometheus?

**Comment by wblakecaldwell** [comment]
I'm sorry, I don't have any experience with Prometheus. I'm sure you could set up InfluxDB and Grafana to do what you want, but it's beyond the scope of this project. Good luck!
