### ISSUE TITLE
grafana dashboard problem

### ISSUE THREAD

**Issue by ghost** [Kentik/docker-monitor#2]
debian 8.3 x64
docker 1.10

![selection_002](https://cloud.githubusercontent.com/assets/13286493/13556283/db222ddc-e3e6-11e5-8801-1f90bcc1d17b.png)
![selection_003](https://cloud.githubusercontent.com/assets/13286493/13556284/db27e9c0-e3e6-11e5-8953-df7bbb0ce36f.png)
![selection_004](https://cloud.githubusercontent.com/assets/13286493/13556285/db2be3f4-e3e6-11e5-9d65-b75c2789ef5b.png)

Can someone help?

**Comment by wblakecaldwell** [comment]
I'll take a look by tomorrow.

**Comment by wblakecaldwell** [comment]
Fixed - thanks for reporting! https://github.com/Kentik/docker-monitor/commit/1ad45501bfa8ce82d3fd08ab7cecaf0bd0f1a4cd

**Comment by egalpin** [comment]
Also seeing this issue with `Docker version 1.11.1` on Mac OS X
