### ISSUE TITLE
Could not work properly to see the data

### ISSUE THREAD

**Issue by starjason** [Kentik/docker-monitor#3]
Could not work properly to see the data

root@ip-10-23-148-81:/home/ubuntu# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

root@ip-10-23-148-81:/home/ubuntu# docker -v
Docker version 1.11.0, build 4dc5990
root@ip-10-23-148-81:/home/ubuntu# docker-compose -v
docker-compose version 1.6.2, build 4d72027

**Comment by wblakecaldwell** [comment]
@starjason Try again - I just updated a bunch of stuff. Thanks!
