### ISSUE TITLE
Cadvisor not posting data to influxdb

### ISSUE THREAD

**Issue by elephunt** [Kentik/docker-monitor#5]
Doing like you write in tutorial,but the cadvisor still does not posting to influxdb. Do i need to attach them to networks?How i know that cadvisor started to talk with influxdb if i cant see in logs?

**Comment by wblakecaldwell** [comment]
@elephunt Thanks for the submission. I'm looking into it!

**Comment by Barty** [comment]
Hi all ! Same issue for me :
- Grafana says "No Datapoints!". 
- cAdvisor works on port 9090.
- I can't access to InfluxDB database cadvisor with login 'root' and password 'root' : "0 error - Could not connect to http://mywebsite.com:8086"
- When I launch ./grafana-influxdb.sh cadvisor ./dashboards/*.json, everything works and it says :+1: 
  "InfluxDB: Database cadvisor already exists
  InfluxDB: Database cadvisor already has the user cadvisor
  Grafana: Data source cadvisor already exists"

Don't know what to do...

Thanks!

**Comment by wblakecaldwell** [comment]
Thanks @Barty. I hope to have this resolved soonish. Thanks!

**Comment by whyming** [comment]
I have the same issue

**Comment by wblakecaldwell** [comment]
@elephunt @Barty @whyming - 

Sorry for the delay. The versions of cadvisor, influxdb, and grafana were so old that stuff was breaking. I bumped all 3 services to more current versions, then updated the shell script for the changes in APIs with #6 

Can you guys try again and lemme know how it goes?
