### ISSUE TITLE
grafana graph is not working 

### ISSUE THREAD

**Issue by asmksf** [Kentik/docker-monitor#7]
Hello there,

 Thanks for your article , i see the cadvisor graph is working after installing in a docker container. but i cant see the graph in grafana -i ran the gra_.sh /grafana-influxdb.sh ./dashboards/_.json from docker host.any idea ?

**Comment by wblakecaldwell** [comment]
Can you fetch the latest changes and try again? Make sure to check the docs - lots changed: no arguments to the script, and dashboards are created for each Docker container it finds. Thanks!
